/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/squadeasy/proxy/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    put: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    post: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    delete: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    options: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    head: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    patch: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/squadeasy/proxy/{*}": {
    get: {
      parameters: {
        path: {
          "*": string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    put: {
      parameters: {
        path: {
          "*": string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    post: {
      parameters: {
        path: {
          "*": string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          "*": string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    options: {
      parameters: {
        path: {
          "*": string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    head: {
      parameters: {
        path: {
          "*": string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    patch: {
      parameters: {
        path: {
          "*": string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/v1/realtime/points": {
    /**
     * Stream live points updates over Server-Sent Events
     * @description Use fetch with the standard Authorization header and read the text/event-stream response body incrementally on the client.
     */
    get: {
      responses: {
        /** @description Default Response */
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/users/points/all": {
    /**
     * Get all stored user point snapshots
     * @description Returns raw stored user point records ordered newest-first. Pass the continuationToken from the previous page to continue exporting.
     */
    get: {
      parameters: {
        query?: {
          limit?: number;
          continuationToken?: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              items: {
                  userId: string;
                  /**
                   * Format: date-time
                   * @description ISO 8601 datetime with timezone offset
                   */
                  time: string;
                  points: number;
                }[];
              continuationToken: string | null;
            };
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              /** @enum {string} */
              error: "Request validation failed";
              details: {
                  path: string;
                  message: string;
                }[];
            };
          };
        };
        /** @description Default Response */
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/users/activity-points/all": {
    /**
     * Get all stored user activity point snapshots
     * @description Returns raw stored user activity point records, including scores and values, ordered newest-first. Pass the continuationToken from the previous page to continue exporting.
     */
    get: {
      parameters: {
        query?: {
          limit?: number;
          continuationToken?: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              items: {
                  userId: string;
                  activityId: string;
                  /**
                   * Format: date-time
                   * @description ISO 8601 datetime with timezone offset
                   */
                  time: string;
                  value: number;
                  points: number;
                }[];
              continuationToken: string | null;
            };
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              /** @enum {string} */
              error: "Request validation failed";
              details: {
                  path: string;
                  message: string;
                }[];
            };
          };
        };
        /** @description Default Response */
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/users/{userId}/activity-points": {
    /** Get a user's activity points */
    get: {
      parameters: {
        query: {
          /** @description ISO 8601 datetime with timezone offset */
          startDate: string;
          /** @description ISO 8601 datetime with timezone offset */
          endDate: string;
        };
        path: {
          userId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
                userId: string;
                activityId: string;
                /**
                 * Format: date-time
                 * @description ISO 8601 datetime with timezone offset
                 */
                time: string;
                value: number;
                points: number;
              }[];
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              /** @enum {string} */
              error: "Request validation failed";
              details: {
                  path: string;
                  message: string;
                }[];
            };
          };
        };
        /** @description Default Response */
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/users/{userId}/points": {
    /** Get a user's total points */
    get: {
      parameters: {
        query: {
          /** @description ISO 8601 datetime with timezone offset */
          startDate: string;
          /** @description ISO 8601 datetime with timezone offset */
          endDate: string;
        };
        path: {
          userId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
                userId: string;
                /**
                 * Format: date-time
                 * @description ISO 8601 datetime with timezone offset
                 */
                time: string;
                points: number;
              }[];
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              /** @enum {string} */
              error: "Request validation failed";
              details: {
                  path: string;
                  message: string;
                }[];
            };
          };
        };
        /** @description Default Response */
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/users/{userId}/activity-visibility": {
    /** Get a user's activity visibility history */
    get: {
      parameters: {
        query: {
          /** @description ISO 8601 datetime with timezone offset */
          startDate: string;
          /** @description ISO 8601 datetime with timezone offset */
          endDate: string;
        };
        path: {
          userId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
                userId: string;
                /**
                 * Format: date-time
                 * @description ISO 8601 datetime with timezone offset
                 */
                time: string;
                isActivityPublic: boolean;
              }[];
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              /** @enum {string} */
              error: "Request validation failed";
              details: {
                  path: string;
                  message: string;
                }[];
            };
          };
        };
        /** @description Default Response */
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/teams/{teamId}/memberships": {
    /** Get a team's user membership history */
    get: {
      parameters: {
        query: {
          /** @description ISO 8601 datetime with timezone offset */
          startDate: string;
          /** @description ISO 8601 datetime with timezone offset */
          endDate: string;
        };
        path: {
          teamId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": ({
                teamId: string;
                userId: string;
                firstName: string;
                lastName: string;
                /**
                 * Format: date-time
                 * @description ISO 8601 datetime with timezone offset
                 */
                joinedAt: string;
                /**
                 * Format: date-time
                 * @description ISO 8601 datetime with timezone offset
                 */
                leftAt: string | null;
                /**
                 * Format: date-time
                 * @description ISO 8601 datetime with timezone offset
                 */
                activeFrom: string;
                /**
                 * Format: date-time
                 * @description ISO 8601 datetime with timezone offset
                 */
                activeUntil: string;
              })[];
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              /** @enum {string} */
              error: "Request validation failed";
              details: {
                  path: string;
                  message: string;
                }[];
            };
          };
        };
        /** @description Default Response */
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/teams/{teamId}/profile": {
    /** Get the latest stored team profile */
    get: {
      parameters: {
        path: {
          teamId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              teamId: string;
              name: string;
              imageUrl: string | null;
              /**
               * Format: date-time
               * @description ISO 8601 datetime with timezone offset
               */
              updatedAt: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/users/{userId}/profile": {
    /** Get the latest stored user profile */
    get: {
      parameters: {
        path: {
          userId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              userId: string;
              firstName: string;
              lastName: string;
              imageUrl: string | null;
              teamId: string;
              teamName: string | null;
              /**
               * Format: date-time
               * @description ISO 8601 datetime with timezone offset
               */
              updatedAt: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/teams/points/all": {
    /**
     * Get all stored team point snapshots
     * @description Returns raw stored team point records ordered newest-first. Pass the continuationToken from the previous page to continue exporting.
     */
    get: {
      parameters: {
        query?: {
          limit?: number;
          continuationToken?: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              items: {
                  teamId: string;
                  /**
                   * Format: date-time
                   * @description ISO 8601 datetime with timezone offset
                   */
                  time: string;
                  points: number;
                }[];
              continuationToken: string | null;
            };
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              /** @enum {string} */
              error: "Request validation failed";
              details: {
                  path: string;
                  message: string;
                }[];
            };
          };
        };
        /** @description Default Response */
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/teams/points": {
    /** Get team points over a time range */
    get: {
      parameters: {
        query: {
          /** @description ISO 8601 datetime with timezone offset */
          startDate: string;
          /** @description ISO 8601 datetime with timezone offset */
          endDate: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
                teamId: string;
                /**
                 * Format: date-time
                 * @description ISO 8601 datetime with timezone offset
                 */
                time: string;
                points: number;
              }[];
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              /** @enum {string} */
              error: "Request validation failed";
              details: {
                  path: string;
                  message: string;
                }[];
            };
          };
        };
        /** @description Default Response */
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
