/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/squadeasy/proxy/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    put: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    post: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    delete: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    options: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    head: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    patch: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/squadeasy/proxy/{*}": {
    get: {
      parameters: {
        path: {
          "*": string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    put: {
      parameters: {
        path: {
          "*": string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    post: {
      parameters: {
        path: {
          "*": string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          "*": string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    options: {
      parameters: {
        path: {
          "*": string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    head: {
      parameters: {
        path: {
          "*": string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    patch: {
      parameters: {
        path: {
          "*": string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/points/stream": {
    /**
     * Stream live points updates over Server-Sent Events
     * @description Use fetch with the standard Authorization header and read the text/event-stream response body incrementally on the client.
     */
    get: {
      responses: {
        /** @description Default Response */
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/user-activity-points/{userId}": {
    /** Get a user's activity points */
    get: {
      parameters: {
        query: {
          /** @description ISO 8601 datetime with timezone offset */
          startDate: string;
          /** @description ISO 8601 datetime with timezone offset */
          endDate: string;
        };
        path: {
          userId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
                userId: string;
                activityId: string;
                /**
                 * Format: date-time
                 * @description ISO 8601 datetime with timezone offset
                 */
                time: string;
                value: number;
                points: number;
              }[];
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              /** @enum {string} */
              error: "Request validation failed";
              details: {
                  path: string;
                  message: string;
                }[];
            };
          };
        };
        /** @description Default Response */
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/user-points/{userId}": {
    /** Get a user's total points */
    get: {
      parameters: {
        query: {
          /** @description ISO 8601 datetime with timezone offset */
          startDate: string;
          /** @description ISO 8601 datetime with timezone offset */
          endDate: string;
        };
        path: {
          userId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
                userId: string;
                /**
                 * Format: date-time
                 * @description ISO 8601 datetime with timezone offset
                 */
                time: string;
                points: number;
              }[];
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              /** @enum {string} */
              error: "Request validation failed";
              details: {
                  path: string;
                  message: string;
                }[];
            };
          };
        };
        /** @description Default Response */
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/team-memberships/{teamId}": {
    /** Get a team's user membership history */
    get: {
      parameters: {
        query: {
          /** @description ISO 8601 datetime with timezone offset */
          startDate: string;
          /** @description ISO 8601 datetime with timezone offset */
          endDate: string;
        };
        path: {
          teamId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": ({
                teamId: string;
                userId: string;
                firstName: string;
                lastName: string;
                image: string | null;
                /**
                 * Format: date-time
                 * @description ISO 8601 datetime with timezone offset
                 */
                joinedAt: string;
                /**
                 * Format: date-time
                 * @description ISO 8601 datetime with timezone offset
                 */
                leftAt: string | null;
                /**
                 * Format: date-time
                 * @description ISO 8601 datetime with timezone offset
                 */
                activeFrom: string;
                /**
                 * Format: date-time
                 * @description ISO 8601 datetime with timezone offset
                 */
                activeUntil: string;
              })[];
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              /** @enum {string} */
              error: "Request validation failed";
              details: {
                  path: string;
                  message: string;
                }[];
            };
          };
        };
        /** @description Default Response */
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/stored-team-profile/{teamId}": {
    /** Get the latest stored team profile */
    get: {
      parameters: {
        path: {
          teamId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              teamId: string;
              name: string;
              imageUrl: string | null;
              /**
               * Format: date-time
               * @description ISO 8601 datetime with timezone offset
               */
              updatedAt: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/stored-user-profile/{userId}": {
    /** Get the latest stored user profile */
    get: {
      parameters: {
        path: {
          userId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              userId: string;
              firstName: string;
              lastName: string;
              imageUrl: string | null;
              teamId: string;
              teamName: string | null;
              /**
               * Format: date-time
               * @description ISO 8601 datetime with timezone offset
               */
              updatedAt: string;
            };
          };
        };
        /** @description Default Response */
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/team-points": {
    /** Get team points over a time range */
    get: {
      parameters: {
        query: {
          /** @description ISO 8601 datetime with timezone offset */
          startDate: string;
          /** @description ISO 8601 datetime with timezone offset */
          endDate: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
                teamId: string;
                /**
                 * Format: date-time
                 * @description ISO 8601 datetime with timezone offset
                 */
                time: string;
                points: number;
              }[];
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              /** @enum {string} */
              error: "Request validation failed";
              details: {
                  path: string;
                  message: string;
                }[];
            };
          };
        };
        /** @description Default Response */
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
